---
- name: COnfigura repositório epel
  shell: rpm -ivh /vagrant/epel-release-latest-7.noarch.rpm
  become: yes

- name: Configura repositório mysql-community
  shell: rpm -ivh /vagrant/mysql80-community-release-el7-1.noarch.rpm
  become: yes

# - name: Configura repositorio mysql
#   yum: name=/vagrant/mysql80-community-release-el7-1.noarch.rpm
#   become: yes

# - name: Configura o repositório epel
#   get_url:
#     url: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#     dest: /vagrant
#     mode: 0440
#   become: yes

# - name: Instala repo epel
#   shell: rpm -ivh epel-release-latest-7.noarch.rpm
#   become: yes
# # 
# - name: 'Instala pacotes de dependencia do sistema operacional'
#   yum:
#     name: "{{ item }}"
#     state: latest
#   become: yes
#   with_items:
#     - mysql
#     - mysql-server
#     - mysql-libs

# - name: 'Cria o banco do MySQL'
  # mysql_db:
    # name: "{{ wp_db_name }}"
    # login_user: root
    # state: present
# 
# - name: 'Cria o usuário do MySQL'
  # mysql_user:
    # login_user: root
    # name: "{{ wp_username }}"
    # password: "{{ wp_user_password }}"
    # priv: "{{ wp_db_name }}.*:ALL"
    # state: present
    # host: "{{ item }}"
  # with_items:
  #  - 'localhost'
  #  - "{{ wp_host_ip }}"
# 
# - name: 'Configura MySQL para aceitar conexões remotas'
#   copy:
#     src: 'roles/mysql/files/my.cnf'
#     dest: '/etc/mysql/my.cnf'
#   become: yes
#   notify:
#     - restart mysql